# default config
baseurl = "http://gilles.gonon.free.fr/"
languageCode = "fr-fr"
title = "Gilles Gonon - Bienvenue"
theme = "parsa"
summaryLength = "10"
paginate = 6
# google analytics
# googleAnalytics = "" # example : UA-123-45

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "plugins/themify-icons/themify-icons.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/headroom/headroom.js"
[[params.plugins.js]]
link = "plugins/instafeed/instafeed.min.js"
[[params.plugins.js]]
link = "plugins/masonry/masonry.js"
[[params.plugins.js]]
link = "plugins/reading-time/readingTime.min.js"
[[params.plugins.js]]
link = "plugins/smooth-scroll/smooth-scroll.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"

# navigation
[[menu.main]]
name = "Accueil"
url = "homepage/home-1"
weight = 1

[[menu.main]]
name = "À propos"
url = ""
weight = 2
hasChildren = true

  [[menu.main]]
  parent = "À propos"
  weight = 2
  name = "🧐 Qui suis-je ?"
  url = "about"

  [[menu.main]]
  parent = "À propos"
  weight = 3
  name = "🎓 CV"
  url = "cv"

  [[menu.main]]
  parent = "À propos"
  weight = 4
  name = "🔖 Publications"
  url = "publications"


[[menu.main]]
name = "Sites Pro"
url = ""
weight = 3
hasChildren = true

  [[menu.main]]
  parent = "Sites Pro"
  weight = 2
  name = "🙀 Le Gueulomaton"
  url = "https://gueulomaton.org"

  [[menu.main]]
  parent = "Sites Pro"
  weight = 3
  name = "🤓 Cours d'informatique"
  url = "https://giloop-projects.gitlab.io/cours-giloop/"

[[menu.main]]
name = "Contact"
url = "contact"
weight = 4



# default parameter
[params]
# List of custom css files
custom_css = ["css/custom.css"]
logo = "images/Texte-Gilles-Gonon.svg"
# logo = "images/logo-gg.jpg"
home = "about"
# theme layout ( two layouts are available, "1" and "2" )
layout = "1"
# Meta data
description = "Site de Gilles Gonon, des réflexions, de la poésie, du code, des expérimentations, des photographies, de la musique ... Retrouvez tout mon petit monde intérieur sur ce site."
images = ["images/gilles-dribble.png", "entete_site6.jpg"]
# Preloader
preloader = true
# search
search = true
# about author
author = "Gilles Gonon"
author_image = "images/gilles-dribble.png"
bio = "L'art rend les gens meilleurs, le cri aussi."
# Contact info
mobile = "+33 6 28 47 23 04"
email = "gilles.gonon@free.fr"
address = "5 avenue des Trente, Tinténiac"
# Contact Form Action
contact_form_action = "https://formspree.io/f/mleoyabr"
# copyright
copyright = "Fait avec 💗 et [Hugo](https://gohugo.io/) par Gilles G. - 2021 original theme by [themefisher](https://themefisher.com)"

# Instagram feed
[params.instafeed]
# enable = true
# access_token = "IGQVJYeUk4YWNIY1h4OWZANeS1wRHZARdjJ5QmdueXN2RFR6NF9iYUtfcGp1NmpxZA3RTbnU1MXpDNVBHTzZAMOFlxcGlkVHBKdjhqSnUybERhNWdQSE5hVmtXT013MEhOQVJJRGJBRURn"

# cookies
[params.cookies]
enable = false
expire_days = 2

# social site
[[params.social]]
icon = "ti-facebook"
url = "https://www.facebook.com/giloop.theloop/"

[[params.social]]
icon = "ti-twitter-alt"
url = "https://twitter.com/giloop"

[[params.social]]
icon = "ti-linkedin"
url = "https://www.linkedin.com/in/gilles-gonon"

[[params.social]]
icon = "ti-github"
url = "https://github.com/giloop"

[[params.social]]
icon = "ti-gitlab"
url = "https://gitlab.com/gilles.gonon"


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4